#!/bin/sh

if test -z "$PYTHON_PATH"
then
	if type python3 >/dev/null 2>&1
	then
		PYTHON_PATH="$(which python3)"
	elif type python >/dev/null 2>&1
	then
		PYTHON_PATH="$(which python)"
	else
		echo >&2 "ERROR: python not installed, cannot run test-tool."
		exit 1
	fi
fi

helper_dir=$(cd "$(dirname $0)" && pwd)
"$PYTHON_PATH" "$helper_dir"/test-tool.py "$@"
