package util

import (
	"bufio"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/git-l10n/git-po-helper/flag"
	"github.com/git-l10n/git-po-helper/gettext"
)

func checkPoCommentEntries(poFile string) ([]string, bool) {
	var (
		errs            []string
		ok              = true
		msgCount        = 0
		commentMsgCount = 0
		badMsgCount     = 0
	)

	f, err := os.Open(poFile)
	if err != nil {
		errs = append(errs, err.Error())
		return errs, false
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.HasPrefix(line, "msgid ") {
			msgCount++
		} else if strings.HasPrefix(line, "#~ msgid ") {
			commentMsgCount++
		} else if strings.HasPrefix(line, "#~| msgid ") {
			badMsgCount++
		}
	}
	if 100*commentMsgCount/msgCount > 1 {
		ok = false
		errs = append(errs, fmt.Sprintf(
			"too many obsolete entries (%d) in comments, please remove them",
			commentMsgCount))
	}
	if badMsgCount > 0 {
		ok = false
		errs = append(errs,
			"remove lines that start with '#~| msgid', for they are not compatible with gettext 0.14")
	}
	return errs, ok
}

func checkPoSyntax(poFile string) ([]string, bool) {
	var (
		progs []string
		errs  []string
		msgs  []string
	)

	if !Exist(poFile) {
		errs = append(errs, fmt.Sprintf(`fail to check "%s", does not exist`, poFile))
		return errs, false
	}

	if flag.GettextUseMultipleVersions() {
		gettext.ShowHints()
	}

	// We want to run "msgfmt" twice using different versions of gettext,
	// because older version of gettext is not compatible with the comments
	// generated by new version of gettext. See:
	//
	//     https://lore.kernel.org/git/874l8rwrh2.fsf@evledraar.gmail.com/
	//
	if app, ok := gettext.GettextAppMap[gettext.VersionDefault]; ok {
		progs = append(progs, app.Program("msgfmt"))
	}
	for version := range gettext.GettextAppHints {
		if app, ok := gettext.GettextAppMap[version]; ok {
			progs = append(progs, app.Program("msgfmt"))
		}
	}
	for version := range gettext.GettextAppMap {
		if version == gettext.VersionDefault {
			continue
		}
		if _, ok := gettext.GettextAppHints[version]; ok {
			continue
		}
		progs = append(progs, gettext.GettextAppMap[version].Program("msgfmt"))
	}
	if len(progs) == 0 {
		errs = append(errs, "no gettext programs found")
		return errs, false
	}

	for idx, prog := range progs {
		cmd := exec.Command(prog,
			"-o",
			os.DevNull,
			"--check",
			"--statistics",
			poFile)
		stderr, err := cmd.StderrPipe()
		if err == nil {
			err = cmd.Start()
		}
		if err != nil {
			errs = append(errs, err.Error())
			return errs, false
		}

		scanner := bufio.NewScanner(stderr)
		for scanner.Scan() {
			line := scanner.Text()
			if len(line) > 0 {
				msgs = append(msgs, line)
			}
		}
		if err = cmd.Wait(); err != nil {
			errs = append(errs, msgs...)
			errs = append(errs, fmt.Sprintf("fail to check po: %s", err))
			return errs, false
		}
		// We may check syntax using different versions of gettext, Eg:
		// gettext 0.14 and new version. Do not report duplicate output
		// messages, such as statistics.
		if idx == 0 {
			errs = append(errs, msgs...)
		}
		msgs = []string{}
	}
	if msgs, ok := checkPoCommentEntries(poFile); !ok {
		errs = append(errs, msgs...)
		return errs, false
	}

	return errs, true
}
